server:
    port: 18081

# Swagger配置
swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /

block:
    ##设定哈希值前difficulty位都是0时,满足计算结果
    difficulty: 4
    ##当前节点p2pserver端口号
    p2pport: 7001
    ##要连接的节点地址
    address: ws://10.8.90.115:7000

    
